# Generated by Django 5.2.8 on 2025-12-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
    ]
